### ISSUE TITLE
Release Builds

### ISSUE THREAD

**Issue by Dontmindmes** [MazeAdmin/Maze#3]
Hey could you post release builds? I have tried everything to compile yet nothing works. Could you compile and post them please

**Comment by Anapher** [comment]
You can find the newest version always on AppVeyor: https://ci.appveyor.com/project/Anapher/maze/builds/24807116/artifacts
I will try to set up the server this week which is needed for this to work.

**Comment by Dontmindmes** [comment]
Wym by server? So the rat won't function with out a server hosted on your part?

**Comment by Anapher** [comment]
The RAT heavily depends on modules that must be downloaded. These modules will be hosted on a server that I must set up first. So no, it does work without this server, but then you have to host the modules yourself.

**Comment by Dontmindmes** [comment]
Ahhh i seee
btw when i attempt to run

> Maze.Administration.exe

nothing happens, am i doing somthing wrong?

**Comment by Dontmindmes** [comment]
Do i need to download all of these? 
https://gyazo.com/1b3d057f111f14cae962dda2cac1c3e0 if so where do i place them?

**Comment by Suvero** [comment]
@Dontmindmes Where U placed these files ? I need help with this too :/
